name: project_by_iago
description: "A Flutter project by iago Lopes."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.7

  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0

  get_it: ^6.0.0
  intl: ^0.20.2
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^10.0.0

  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/raro_labs_logo.png"
  adaptive_icon_foreground: "assets/images/raro_labs_logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
